cnn:
  embedding_dim: 128
  max_len: 200
  num_words_in_vocab: 5_000
  num_epochs: 50
  num_folds: 10
  batch_size: 128
  UseClassWeights: False
  LR: 0.0005
  dilation: 2
  best_epoch: 37
bigru:
  embedding_dim: 256
  max_len: 200
  num_words_in_vocab: 5_000
  num_epochs: 15
  num_folds: 10
  Class: 'aortic_regurgitation' # aortic_regurgitation, lv_sys_func, None to run all
  batch_size: 128
  UseClassWeights: False
  LR: 0.005
  dilation: 4
  num_layers: 96
  lemmatize: True
  lowercase: False
  pre_trained_embeddings: False

